### ISSUE TITLE
[Feature Request] Ability to shorten the height of the block

### ISSUE THREAD

**Issue by LouCodingStuff** [yusanshi/emgithub#26]
i want there to be a way that you can change the hieght of the block of code so that when its embeded on a webpage it doesnt take up the entire thing

**Comment by yusanshi** [comment]
Sorry but I didn't get it. Could you post the screenshot what is looks now?

**Comment by LouCodingStuff** [comment]
its ok i was being dumb, thanks for your quick response though

**Comment by LouCodingStuff** [comment]
its ok i was being dumb, thanks for your quick response though
